### PR TITLE
Solução para o desafio 5

### PR DESCRIPTION
**Pull request by Mekylei-Belchior**
Submetendo solução em Python para o desafio 5.

### CODE REVIEW

**Comment by Mekylei-Belchior** [comment]
Boa noite @BernardinoCampos, tudo bem? Testei na minha máquina e no Repl.it e está rodando. Poderia verificar, por favor?

https://repl.it/@mekylei/desafio5

**Comment by BernardinoCampos** [comment]
Continua exatamente o mesmo erro, vc baixou o arquivo de 10K que está no site  que te indiquei?

Presta atenção as mensagens de erro, o erro está na linha abaixo

gmax = dados[dados['salario'] == dados['salario'].max()][['nome', 'sobrenome', 'salario']]

Traceback (most recent call last):
  File "Exec/Python-Mekylei-Belchior.py", line 107, in <module>
    main(sys.argv[1])
  File "Exec/Python-Mekylei-Belchior.py", line 99, in main
    geral(dados)
  File "Exec/Python-Mekylei-Belchior.py", line 15, in geral
    gmax = dados[dados['salario'] == dados['salario'].max()][['nome', 'sobrenome', 'salario']]
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/frame.py", line 2924, in __getitem__
    raise_missing=True)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['nome'] not in index"

**Comment by Mekylei-Belchior** [comment]
Boa tarde @BernardinoCampos! Acabei enrolando para dar o push dos reajustes que havia feito no código. Verifiquei o hash pelo CMD do Windows e ainda não está batendo. Poderia rodar na sua máquina e verificar a saída para mim?

**Comment by BernardinoCampos** [comment]
Não está deixando eu subir o diff todo, vou mandar só um pedaço, já deve dar uma idéia

4855c4855
< last_name_max|Wion|Aahron Wion|60543.22
---
> last_name_max|Wion|Aakash Wion|60543.22
4857,4858c4857,4858
< last_name_max|Wit|Aahron Wit|94478.09
< last_name_max|Wolf|Aahron Wolf|8811.63
---
> last_name_max|Wit|Aakash Wit|94478.09
> last_name_max|Wolf|Aakash Wolf|8811.63
4860,4865c4860,4865
< last_name_max|Wolff|Aahron Wolff|43750.83
< last_name_max|Wong|Aahron Wong|96089.73
< last_name_max|Wood|Aahron Wood|85592.44
< last_name_max|Woodard|Aahron Woodard|75016.73
< last_name_max|Woods|Aahron Woods|80733.38
< last_name_max|Woodward|Aahron Woodward|37629.01
---
> last_name_max|Wolff|Aakash Wolff|43750.83
> last_name_max|Wong|Aakash Wong|96089.73
> last_name_max|Wood|Aakash Wood|85592.44
> last_name_max|Woodard|Aakash Woodard|75016.73
> last_name_max|Woods|Aakash Woods|80733.38
> last_name_max|Woodward|Aakash Woodward|37629.01
4868c4868
< last_name_max|Wyatt|Aahron Wyatt|72343.10
---
> last_name_max|Wyatt|Aakash Wyatt|72343.10
4870,4871c4870,4871
< last_name_max|Yates|Aahron Yates|66075.84
< last_name_max|Yoder|Aahron Yoder|99686.28
---
> last_name_max|Yates|Aakash Yates|66075.84
> last_name_max|Yoder|Aakash Yoder|99686.28
4873,4874c4873,4874
< last_name_max|York|Aahron York|69329.49
< last_name_max|Young|Aahron Young|8398.21
---
> last_name_max|York|Aakash York|69329.49
> last_name_max|Young|Aakash Young|8398.21
4876,4879c4876,4879
< last_name_max|Yu|Aahron Yu|43703.72
< last_name_max|Zacchi|Aahron Zacchi|59220.79
< last_name_max|Zaganelli|Aahron Zaganelli|65317.95
< last_name_max|Zaia|Aahron Zaia|43567.02
---
> last_name_max|Yu|Aakash Yu|43703.72
> last_name_max|Zacchi|Aakash Zacchi|59220.79
> last_name_max|Zaganelli|Aakash Zaganelli|65317.95
> last_name_max|Zaia|Aakash Zaia|43567.02
4886c4886
< last_name_max|Zanardo|Aahron Zanardo|39860.74
---
> last_name_max|Zanardo|Aakash Zanardo|39860.74
4889,4890c4889,4890
< last_name_max|Zancanela|Aahron Zancanela|92940.40
< last_name_max|Zanchetin|Aahron Zanchetin|89489.40
---
> last_name_max|Zancanela|Aakash Zancanela|92940.40
> last_name_max|Zanchetin|Aakash Zanchetin|89489.40
4893c4893
< last_name_max|Zandonadi|Aahron Zandonadi|99875.12
---
> last_name_max|Zandonadi|Aakash Zandonadi|99875.12
4895c4895
< last_name_max|Zanellato|Aahron Zanellato|98165.32
---
> last_name_max|Zanellato|Aakash Zanellato|98165.32
4897,4898c4897,4898
< last_name_max|Zanichelli|Aahron Zanichelli|77137.08
< last_name_max|Zanivan|Aahron Zanivan|82801.56
---
> last_name_max|Zanichelli|Aakash Zanichelli|77137.08
> last_name_max|Zanivan|Aakash Zanivan|82801.56
4901,4902c4901,4902
< last_name_max|Zanoni|Aahron Zanoni|92764.11
< last_name_max|Zantonelli|Aahron Zantonelli|43694.08
---
> last_name_max|Zanoni|Aakash Zanoni|92764.11
> last_name_max|Zantonelli|Aakash Zantonelli|43694.08
4904,4906c4904,4906
< last_name_max|Zavala|Aahron Zavala|89330.76
< last_name_max|Zavarise|Aahron Zavarise|78281.97
< last_name_max|Zavarize|Aahron Zavarize|73791.41
---
> last_name_max|Zavala|Aakash Zavala|89330.76
> last_name_max|Zavarise|Aakash Zavarise|78281.97
> last_name_max|Zavarize|Aakash Zavarize|73791.41
4909,4912c4909,4912
< last_name_max|Zerboni|Aahron Zerboni|90348.30
< last_name_max|Zhang|Aahron Zhang|80859.35
< last_name_max|Zicardi|Aahron Zicardi|75898.37
< last_name_max|Ziegler|Aahron Ziegler|72983.35
---
> last_name_max|Zerboni|Aakash Zerboni|90348.30
> last_name_max|Zhang|Aakash Zhang|80859.35
> last_name_max|Zicardi|Aakash Zicardi|75898.37
> last_name_max|Ziegler|Aakash Ziegler|72983.35
4914c4914
< last_name_max|Zimmermann|Aahron Zimmermann|96323.31
---
> last_name_max|Zimmermann|Aakash Zimmermann|96323.31
4917,4918c4917,4918
< last_name_max|Zoppi|Aahron Zoppi|59395.82
< last_name_max|Zorzal|Aahron Zorzal|69731.58
---
> last_name_max|Zoppi|Aakash Zoppi|59395.82
> last_name_max|Zorzal|Aakash Zorzal|69731.58
4922c4922
< last_name_max|Zucoloto|Aahron Zucoloto|70490.44
---
> last_name_max|Zucoloto|Aakash Zucoloto|70490.44
4925c4925
< last_name_max|Zuza|Aahron Zuza|34012.40
---
> last_name_max|Zuza|Aakash Zuza|34012.40

**Pull request closed without merging**
