### PR TITLE
Desafio 5

### PR DESCRIPTION
**Pull request by JonathasValeriano**
Modificações destinadas a performance
Remoção de trailing spaces

### CODE REVIEW

**Review by BernardinoCampos — CHANGES_REQUESTED** [review]
Deu erro:

g++ -m64 -std=c++11 -pthread -Ofast -ftree-vectorize -funroll-loops -faggressive-loop-optimizations -o d5 -Ithird_part *.cpp
main.cpp:193:50: error: array must be initialized with a brace-enclosed initializer
     std::array<Area, 2> areas = { Area(), Area() };
                                                  ^
main.cpp:193:50: error: too many initializers for ‘std::array<Area, 2ul>’
In file included from /usr/include/c++/4.8.2/atomic:41:0,
                 from TimedTasksQueue.hpp:18,
                 from TimedTasksQueue.cpp:7:
/usr/include/c++/4.8.2/bits/atomic_base.h: In static member function ‘static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes ...) [with _Functor = TTasks::TimedTasksQueue::queueLoop()::__lambda1; _ArgTypes = {TTasks::Task&&}]’:
/usr/include/c++/4.8.2/bits/atomic_base.h:496:35: error: invalid memory model for ‘__atomic_load’
  return __atomic_load_n(&_M_i, __m);

**Comment by JonathasValeriano** [comment]
Fechando para reorganização do código.

**Review by BernardinoCampos — CHANGES_REQUESTED** [review]
Race Condition

**Review by BernardinoCampos — APPROVED** [review]
Aprovado "Cum laude"

**Pull request merged**
